### ISSUE TITLE
automatic update by You Tube by Taapat

### ISSUE THREAD

**Issue by endzis77** [Taapat/enigma2-plugin-youtube#110]
Hi,
First of all, thank you for fantastic plugin.
But, You Tube changes somethig every tme. 
Could You add to You Tube plugin automatic update function?
Thak You in advance.

**Comment by Taapat** [comment]
Hi,
A plugin is provided to watch youtube instead of packet management.
Package management must be supported by your image.


If in your image feed automatic package update is not supported, please contact your image developer.
If your image is not supported, you can choose another image or install plugin packages manually.
You can update them only when something stops working. You do not have to install each version.


In all plugins in which I've seen a plugin update in a plugin, I have the impression that their developers have a very poor understanding of the process how an image is built.
