### ISSUE TITLE
FATAL SIGNAL error.

### ISSUE THREAD

**Issue by 68foxboris** [Taapat/enigma2-plugin-youtube#235]
On my home build, the application crashes with an error after a short run. Receiver Pulse4K mini.

21:46:23.6156 [ePicLoad] decode picture... /tmp/91WRoB6SOBI.jpg

libgomp: Thread creation failed: Resource temporarily unavailable
21:46:23.6202 [gRC] Waiting for gRC thread shutdown.
21:46:23.6204 [gRC] Thread has finished.
21:46:23.6591 PC: b62d4df8
21:46:23.6592 Fault Address: 00000004
21:46:23.6592 Error Code:: 23
21:46:23.6594 Backtrace:
21:46:23.6597 enigma2(_Z17handleFatalSignaliP9siginfo_tPv) [0x7DD2C]
21:46:23.6598 /lib/libc.so.6(__default_rt_sa_restorer) [0xB5EAB070]
21:46:23.6598 -------FATAL SIGNAL

Checked on ET11000 4k.It lasted much longer, but froze and only the shutdown button helped.

22:00:44.9472 [eServiceMP3] starting pipeline

(enigma2:1984): GStreamer-WARNING **: 22:00:44.955: failed to create thread: Error creating thread: Resource temporarily unavailable
22:00:48.6254 [gRC] Warning: Main thread is busy, displaying spinner!

**Comment by Taapat** [comment]
I assume you are using one of the newer versions of enigma.
Therefore, I recommend paying attention to why the plugin uses ePicLoad instead of LoadPixmap to display images.
If you use your own skin, try the default one from the plugin.

A long time ago I fixed the ePicLoad segmentation fault on osmio4k: https://github.com/Taapat/enigma2-plugin-youtube/commit/451a72525195fa24c6ba35db700142a2a2062c7d
You can try increasing the time here: https://github.com/Taapat/enigma2-plugin-youtube/blob/master/src/YouTubeUi.py#L606
Maybe this will help you.

However, I would recommend using LoadPixmap in the plugin because it works much faster and more stable in my opinion.
For this, image must support svg and use in skin flags=BT_SCALE for thumbnail.

**Comment by 68foxboris** [comment]
There are no problems with the default skin yet.
