### ISSUE TITLE
Has anyone managed to get this working again?.

### ISSUE THREAD

**Issue by jones873** [Taapat/enigma2-plugin-youtube#251]
As the title says has anyone got this working again since the last update thanks

**Comment by alabre** [comment]
It was running fine on 2024-10-10 right after installing the new version.
Yesterday, once the old behaviour with the "could not find the video URL" came up. In all other cases there was a short black screen and then the search result list

This morning I played around a bit. Choosing the gstreamer player worked for me. A live stream came in in HD, other videos played in 360px.

So, the answer is "yes" but with the same results as before. Something's still going on there...

**Comment by jones873** [comment]
Thanks for getting back to me, looks like we will have to wait for taapat to resolve the issue

**Comment by StifflersMom** [comment]
![grafik](https://github.com/user-attachments/assets/1ce6a50a-bf33-4624-b1ae-71472b4fd778)

The only way to fix this will be to mux the audio stream (format 251) with the voideo (format 137).
It's easy with ffmpeg (-i audiotrack -i videotrack -c copy destinationfile).
On my Vu+ zero 4k ffmpeg is installed but every video has to be stored temporarily for muxing the different tracks together because afaik you can't do the muxing with ffmpeg through a pipe...
