### ISSUE TITLE
#YouTube_Playback_Issues_(no_sound_stuttering/lagging_sound)!

### ISSUE THREAD

**Issue by S4iyan3lit3** [Taapat/enigma2-plugin-youtube#48]
Greetings!

I was recognized an issue with playback...

There is no sound or the sound was lagging / stuttering on video playbacks where is a real videoclipp and not just a static image background on YouTube video...basically the YouTube app did not crash,so there is no crash log...

Unfortunately I cant debug this problem...I need advice's / help for TryFix-ing or debugging thes issue...

Tested with the following YouTube video on VU+ Zero STB. with VTI 13 and VTI 14 Images!

(Test - Video Used for experiment...and it's working flawlessly on personal computer...only YouTube app have playback issues with it...)

Filatov & Karas - Time Won't Wait (Lyric Video) 
https://www.youtube.com/watch?v=Zj_hXV_o8Fo

(Sorry for grammatical issues..)

Wish God Blessed Nice Day!

Regards!

**Comment by Taapat** [comment]
I don't have problems on OpenPL.
![screenshot](https://user-images.githubusercontent.com/1623947/49341110-a4a71f80-f651-11e8-82f3-c549c3f83295.jpg)

I think you have the same problem as here: https://github.com/Taapat/enigma2-plugin-youtube/issues/46
Vti just like Blackhole is cloused source image, so I can not help anything.
Sorry!

**Comment by nunigaia** [comment]
@Taapat 

BlackHole is currently playing videos, although " there´s no sound " ... do you need any special file from blackhole in order to make it working ( FIX )?

If so, and of course  if you can collaborate with this issue, we can send you the files you need it!

best regards
nunigaia
(Bh Team )

**Comment by Taapat** [comment]
To check and answer something, first I want to see the enigma2 source code.
In it I can see what and how is realized.

I have no interest in spending time with closed source images, in which I can only guess how something work there.
I've already pointed to a basic commit in with I add suburi support in service reference which is used in this plugin: https://github.com/OpenPLi/enigma2/commit/65962a39625aaf02f66ee9258181ec2d164916a6
Maybe some more changes are needed but I don't know because the source codes are not available.

**Comment by nunigaia** [comment]
I knew that, and then it was possible to port the video! Hope we all can port, also audio :)

best regards
nunigaia
(BH team)



thanks, @Taapat

**Comment by nunigaia** [comment]
> 
> 
> To check and answer something, first I want to see the enigma2 source code.
> In it I can see what and how is realized.
> 
> I have no interest in spending time with closed source images, in which I can only guess how something work there.
> I've already pointed to a basic commit in with I add suburi support in service reference which is used in this plugin: [OpenPLi/enigma2@65962a3](https://github.com/OpenPLi/enigma2/commit/65962a39625aaf02f66ee9258181ec2d164916a6)
> Maybe some more changes are needed but I don't know because the source codes are not available.

Hi Madars,

Can you please investigate the servicemp3.cpp ( BlackHole 3.0.8A ) ... lastest image, in order to have sound!

Attached all the " service folder " files.

[service.zip](https://github.com/Taapat/enigma2-plugin-youtube/files/2890597/service.zip)

Thanks for all,
If you need something more, even for testing it on severall Vuplus STB´S  ... please don´t hesitate ... quote this issue, and i will stay in touch.

All the best,
nunigaia
( BH Team )

**Comment by Taapat** [comment]
I think that the problem is in servicemp3.cpp here:
```
		g_object_set (G_OBJECT (m_gst_playbin), "uri", uri, NULL);
		g_free(uri);
		if (suburi != NULL)
			g_free(suburi);

		GstElement *subsink = gst_element_factory_make("subsink", "subtitle_sink");
```
You free suburi before set it.
Delete g_free(suburi) there and use after:
`g_object_set (G_OBJECT (m_gst_playbin), "suburi", suburi, NULL);`

**Comment by Taapat** [comment]
Not tested but this should work:
[servicemp3.cpp.zip](https://github.com/Taapat/enigma2-plugin-youtube/files/2890916/servicemp3.cpp.zip)

**Comment by nunigaia** [comment]
> 
> 
> Not tested but this should work:
> [servicemp3.cpp.zip](https://github.com/Taapat/enigma2-plugin-youtube/files/2890916/servicemp3.cpp.zip)

I will try, and then i will let you know!
Thanks Madars

**Comment by nunigaia** [comment]
@Taapat ( Madars Auns )

Many thanks for your colaboration.
The BlackHole Team wants to thank and take you current that youtube ( your plugin ), is currently tested and working at BlackHole Image ( version 3.0.8A ), and the implementation should be done on the next release.

Many thanks for all and for your effort

Best regards
nunigaia BH team
