### ISSUE TITLE
Handling exteplayer3 directly

### ISSUE THREAD

**Issue by ozone1864** [Taapat/enigma2-plugin-youtube#84]
Dear @Taapat ,
I got serviceapp installed but since I am using Zgemma H9S box based on hisilicon chip, its recommended to keep the playback system as default in serviceapp.
Youtube plugin doesn"t work with hisilicon service player.
I got exteplayer3 installed is there a way to allow youtube plugin handle exteplayer3 without the need to switch from serviceapp ?

Regards,

**Comment by ozone1864** [comment]
Can this happen @Taapat ?
Serviceapp is installed and exteplayer3 too. But its switched to original player.
Can you make the youtube handle exteplayer3 without the need to switch from default to exteplayer3 ?

**Comment by Taapat** [comment]
I don't like the additional config option for the user.
Any additional config option indicates a poorly crafted solution.
I also don't like unnecessary dependencies on other plugins.


However, due to the specifics of hisilicon, I will probably introduce an additional config option to select exteplayer3 for playback.

**Comment by ozone1864** [comment]
> I don't like the additional config option for the user.
> Any additional config option indicates a poorly crafted solution.
> I also don't like unnecessary dependencies on other plugins.
> 
> However, due to the specifics of hisilicon, I will probably introduce an additional config option to select exteplayer3 for playback.

Thanks alot man ! waiting the update
